name: Bug report
description: Report a reproducible issue
labels: [bug]
body:
  - type: textarea
    id: current
    attributes:
      label: Current behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
